### ISSUE TITLE
Tracking inputs vs outputs and viceversa

### ISSUE THREAD

**Issue by dvd101x** [felipec/math-notepad#1]
There are a few inputs that evaluate in multiple output lines and some that generate an output that is not very useful. So it can be difficult to track input vs outputs and vice versa.

Input:

```
"a string\nwith three\nlines"
help(sum)
2
f(x,y) = x+y
f(1,2)
a = 10;
b = a 2
[1,2;3,4]
car = {}
car.mass = 10 kg
temperatures = []
temperatures[1] = 20 degF
temperatures[2] = 40 degC
temperatures
```

Output:
```
a string
with three
lines

Name: sum

Category: Statistics

Description:
    Compute the sum of all values.

Syntax:
    sum(a, b, c, ...)
    sum(A)

Examples:
    sum(2, 3, 4, 1)
        10
    sum([2, 3, 4, 1])
        10
    sum([2, 5; 4, 3])
        14

See also: max, mean, median, min, prod, std, sum, variance

2
function e(t,r){return(arguments.length===z&&m(t)&&b(r)?O:arguments.length===R&&d(t)&&w(r)?_:arguments.length===q&&y(t)&&N(r)?C:arguments.length===B&&g(t)&&M(r)?T:arguments.length===D&&v(t)&&E(r)?I:arguments.length===j&&x(t)&&S(r)?k:a).apply(e,arguments)}
3
[]
20
[[1, 2], [3, 4]]
[object Object]
10 kg
[]
20 degF
40 degC
[20 degF, 40 degC]
```
An alternative could be to mark from which input we are receiving the output and don't show the null/not useful outputs like this.
```
1:	"a string
	with three
	lines"
2:	
	Name: sum
	
	Category: Statistics
	
	Description:
	    Compute the sum of all values.
	
	Syntax:
	    sum(a, b, c, ...)
	    sum(A)
	
	Examples:
	    sum(2, 3, 4, 1)
	        10
	    sum([2, 3, 4, 1])
	        10
	    sum([2, 5; 4, 3])
	        14
	
	See also: max, mean, median, min, prod, std, sum, variance
	
3:	2
5:	3
7:	20
8:	[[1, 2], [3, 4]]
10:	10 kg
12:	20 degF
13:	40 degC
14:	[20 degF, 40 degC]
```

I have a working version but the code is not very nice and I don't know how to include line numbers on the input.

**Comment by dvd101x** [comment]
I changed my mind, there must be a better way.

**Comment by felipec** [comment]
I don't particularly find useful to use strings on a math notepad--nor multiple-line outputs such as `help()`, but it's true that right now they aren't handled well.

Personally I would force multiple lines to become one line, even if they aren't particularly readable.

So that `"a string\nwith three\nlines"` becomes `"a string\nwith three\nlines"`.

**Comment by dvd101x** [comment]
Ok, I was looking into it with a different approach.

I’m working on a code where one line of input could be one line of output, many lines of output, really long lines of output or no lines of output as mathjs is very broad. Nonetheless I understand this might not the intention and there is a certain beauty and simplicity with this notebook approach.

I was working on a code that implements it as numbered lines to match input and output but isn’t as clean. I was thing about highlighting the output line from the current input for it to be more visual but I have no idea of how to do that.

Thanks for reviewing this, for me it’s ok to close this issue at any time.

**Comment by felipec** [comment]
There may be some value in this enhancement, but my use cases are one-line only, so I don't see it.

I personally don't see much value in:

```
"a string
with three
lines"
```

But perhaps there could be some value in other use cases. Do you have an example?

**Comment by dvd101x** [comment]
The most relevant ways for me are the display of help files, the formating of ouputs and for long ouputs when using word wrap.

```python
x= (0:10:90) deg;
help(sin)
concat("sin(",format(x,6),") = \n",format(sin(x),6))
````
Returns

```javascript
[]

Name: sin

Category: Trigonometry

Description:
    Compute the sine of x in radians.

Syntax:
    sin(x)

Examples:
    sin(2)
        0.90929742682568
    sin(pi / 4) ^ 2
        0.5
    sin(90 deg)
        1
    sin(30 deg)
        0.5
    sin(0.2)^2 + cos(0.2)^2
        1

See also: asin, cos, tan

"sin([0 deg, 10 deg, 20 deg, 30 deg, 40 deg, 50 deg, 60 deg, 70 deg, 80 deg, 90 deg]) = 
[0, 0.173648, 0.34202, 0.5, 0.642788, 0.766044, 0.866025, 0.939693, 0.984808, 1]"
```

**Comment by felipec** [comment]
The `help` use case does make sense, but there are better ways of handling help. I've pushed a commit that deals with this:

![math-help](https://user-images.githubusercontent.com/8358/151720740-7c7e7e8a-6a32-4f1b-89d7-1b564729429f.png)

**Comment by dvd101x** [comment]
In the end I found a way to match inputs and outputs. I think it might show the utility of multiple line inputs and outputs.

Some expressions might be complex and some answers also might be complex.

https://github.com/dvd101x/web-thermodynamics

Nonetheless I see most examples of MathJS implementations evaluating line by line and might be a matter of preference. We could agree to disagree and close this issue.
